## YAML Template.
---
## YAML Template.
server:
    port: 8004
    
    
spring:
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
 
      
activiti:
    datasource:        
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 5
        maximumPoolSize: 300
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:            
            dataUrl: jdbc:mysql://bd-prd-portal-atendimento-matrix.mysql.database.azure.com:3306/activiti?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Cuiaba&useLegacyDatetimeCode=false&autoReconnect=true            
            dataSourceUser: bd_prd_admin@bd-prd-portal-atendimento-matrix
            dataSourcePassword: yR5q8kmc
            port: 3306            
            connectionTestQuery: SELECT 1  
 
matrix:
    datasource:        
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 5
        maximumPoolSize: 300
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:            
            dataUrl: jdbc:mysql://bd-prd-portal-atendimento-matrix.mysql.database.azure.com:3306/matrix?rewriteBatchedStatements=true&useTimezone=true&serverTimezone=America/Cuiaba&useLegacyDatetimeCode=false&autoReconnect=true            
            dataSourceUser: bd_prd_admin@bd-prd-portal-atendimento-matrix
            dataSourcePassword: yR5q8kmc
            port: 3306            
            connectionTestQuery: SELECT 1  
  
wbc:
    datasource:        
        socketTimeout: 30000
        loginTimeout: 30000
        minimumIdle: 5
        maximumPoolSize: 300
        validationTimeout: 10000
        idleTimeout: 10000
        connectionTimeout: 30000
        autoCommit: false
        initializationFailFast: false        
        sqlserver:            
            dataUrl: jdbc:sqlserver://192.168.0.22;databaseName=WBC_ENERGY_DB;user=matrix_portal;password=portal_matrix
            dataSourceUser: matrix_portal
            dataSourcePassword: portal_matrix
            port: 3306            
            connectionTestQuery: SELECT 1   
            
email:
    host: smtp.office365.com
    port: 587
    username: portal@matrixenergia.com
    password: M@atrix2@2@
    auth: true  
    protocol: smtp
    starttls:
           enable: true
           required: true      
           
websocket:
        cors:
            origin: http://localhost:8080    
            
portal:
        url:  http://localhost:8080/troca-senha            